// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"gdb-withall-bug/internal/dao/internal"
	"gdb-withall-bug/internal/model/entity"
)

// internalPostDao is internal type for wrapping internal DAO implements.
type internalPostDao = *internal.PostDao

// postDao is the data access object for table post.
// You can define custom methods on it to extend its functionality as you wish.
type postDao struct {
	internalPostDao
}

var (
	// Post is globally public accessible object for table post operations.
	Post = postDao{
		internal.NewPostDao(),
	}
)

// Fill with you ideas below.

func (d postDao) Get(ctx context.Context, id int64) (entity.PostWithUser, error) {
	var data entity.PostWithUser
	err := d.Ctx(ctx).WithAll().Where(d.Columns().Id, id).Scan(&data)
	return data, err
}
